<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class DaftarKelasSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('daftar_kelas')->insert([
            [
                'kodeKelas' => 'SI4102',
                'kapasitas' => '40',
                'kodeMK' => 'IS184414',
                'kelas' => 'A',
                'dosenNRP' => '5026232',
            ],
            [
                'kodeKelas' => 'SI4102',
                'kapasitas' => '40',
                'kodeMK' => 'IS184414',
                'kelas' => 'B',
                'dosenNRP' => '5026232',
            ],
            [
                'kodeKelas' => 'SI4102',
                'kapasitas' => '40',
                'kodeMK' => 'IS184414',
                'kelas' => 'C',
                'dosenNRP' => '5026232',
            ],
            [
                'kodeKelas' => 'SI4102',
                'kapasitas' => '40',
                'kodeMK' => 'IS184414',
                'kelas' => 'D',
                'dosenNRP' => '5026234',
            ],
            [
                'kodeKelas' => 'SI4102',
                'kapasitas' => '40',
                'kodeMK' => 'IS184414',
                'kelas' => 'I',
                'dosenNRP' => '5026234',
            ],
            [
                'kodeKelas' => 'SI4101',
                'kapasitas' => '35',
                'kodeMK' => 'IS184412',
                'kelas' => 'A',
                'dosenNRP' => '5026201',
            ],
            [
                'kodeKelas' => 'SI4101',
                'kapasitas' => '35',
                'kodeMK' => 'IS184412',
                'kelas' => 'B',
                'dosenNRP' => '5026201',
            ],
            [
                'kodeKelas' => 'SI4101',
                'kapasitas' => '35',
                'kodeMK' => 'IS184412',
                'kelas' => 'C',
                'dosenNRP' => '5026201',
            ],
            [
                'kodeKelas' => 'SI4101',
                'kapasitas' => '35',
                'kodeMK' => 'IS184412',
                'kelas' => 'D',
                'dosenNRP' => '5026203',
            ],
            [
                'kodeKelas' => 'SI4101',
                'kapasitas' => '35',
                'kodeMK' => 'IS184412',
                'kelas' => 'I',
                'dosenNRP' => '5026203',
            ],
            [
                'kodeKelas' => 'SI2202',
                'kapasitas' => '40',
                'kodeMK' => 'IW184301',
                'kelas' => 'A',
                'dosenNRP' => '5026221',
            ],
            [
                'kodeKelas' => 'SI2202',
                'kapasitas' => '40',
                'kodeMK' => 'IW184301',
                'kelas' => 'B',
                'dosenNRP' => '5026221',
            ],
            [
                'kodeKelas' => 'SI2202',
                'kapasitas' => '40',
                'kodeMK' => 'IW184301',
                'kelas' => 'C',
                'dosenNRP' => '5026221',
            ],
            [
                'kodeKelas' => 'SI2202',
                'kapasitas' => '40',
                'kodeMK' => 'IW184301',
                'kelas' => 'D',
                'dosenNRP' => '5026229',
            ],
            [
                'kodeKelas' => 'SI2202',
                'kapasitas' => '40',
                'kodeMK' => 'IW184301',
                'kelas' => 'I',
                'dosenNRP' => '5026229',
            ],
            [
                'kodeKelas' => 'SI1101',
                'kapasitas' => '40',
                'kodeMK' => 'IS184309',
                'kelas' => 'A',
                'dosenNRP' => '5026211',
            ],
            [
                'kodeKelas' => 'SI1101',
                'kapasitas' => '40',
                'kodeMK' => 'IS184309',
                'kelas' => 'B',
                'dosenNRP' => '5026211',
            ],
            [
                'kodeKelas' => 'SI1101',
                'kapasitas' => '40',
                'kodeMK' => 'IS184309',
                'kelas' => 'C',
                'dosenNRP' => '5026211',
            ],
            [
                'kodeKelas' => 'SI1101',
                'kapasitas' => '40',
                'kodeMK' => 'IS184309',
                'kelas' => 'D',
                'dosenNRP' => '5026211',
            ],
            [
                'kodeKelas' => 'SI1101',
                'kapasitas' => '40',
                'kodeMK' => 'IS184309',
                'kelas' => 'I',
                'dosenNRP' => '5026211',
            ],
            [
                'kodeKelas' => 'SI4101',
                'kapasitas' => '40',
                'kodeMK' => 'IS184204',
                'kelas' => 'A',
                'dosenNRP' => '5026223',
            ],
            [
                'kodeKelas' => 'SI4101',
                'kapasitas' => '40',
                'kodeMK' => 'IS184204',
                'kelas' => 'B',
                'dosenNRP' => '5026223',
            ],
            [
                'kodeKelas' => 'SI4101',
                'kapasitas' => '40',
                'kodeMK' => 'IS184204',
                'kelas' => 'C',
                'dosenNRP' => '5026223',
            ],
            [
                'kodeKelas' => 'SI4101',
                'kapasitas' => '40',
                'kodeMK' => 'IS184204',
                'kelas' => 'D',
                'dosenNRP' => '5026228',
            ],
            [
                'kodeKelas' => 'SI4101',
                'kapasitas' => '40',
                'kodeMK' => 'IS184204',
                'kelas' => 'I',
                'dosenNRP' => '5026228',
            ],
            [
                'kodeKelas' => 'SI4201',
                'kapasitas' => '40',
                'kodeMK' => 'IS184308',
                'kelas' => 'A',
                'dosenNRP' => '5026213',
            ],
            [
                'kodeKelas' => 'SI4201',
                'kapasitas' => '40',
                'kodeMK' => 'IS184308',
                'kelas' => 'B',
                'dosenNRP' => '5026213',
            ],
            [
                'kodeKelas' => 'SI4201',
                'kapasitas' => '40',
                'kodeMK' => 'IS184308',
                'kelas' => 'C',
                'dosenNRP' => '5026213',
            ],
            [
                'kodeKelas' => 'SI4201',
                'kapasitas' => '40',
                'kodeMK' => 'IS184308',
                'kelas' => 'D',
                'dosenNRP' => '5026214',
            ],
            [
                'kodeKelas' => 'SI4201',
                'kapasitas' => '40',
                'kodeMK' => 'IS184308',
                'kelas' => 'I',
                'dosenNRP' => '5026214',
            ],
            [
                'kodeKelas' => 'SI2101',
                'kapasitas' => '40',
                'kodeMK' => 'IS184310',
                'kelas' => 'A',
                'dosenNRP' => '5026234',
            ],
            [
                'kodeKelas' => 'SI2101',
                'kapasitas' => '40',
                'kodeMK' => 'IS184310',
                'kelas' => 'B',
                'dosenNRP' => '5026234',
            ],
            [
                'kodeKelas' => 'SI2101',
                'kapasitas' => '40',
                'kodeMK' => 'IS184310',
                'kelas' => 'C',
                'dosenNRP' => '5026234',
            ],
            [
                'kodeKelas' => 'SI2101',
                'kapasitas' => '40',
                'kodeMK' => 'IS184310',
                'kelas' => 'D',
                'dosenNRP' => '502623',
            ],
            [
                'kodeKelas' => 'SI2101',
                'kapasitas' => '40',
                'kodeMK' => 'IS184310',
                'kelas' => 'I',
                'dosenNRP' => '502623',
            ],
            [
                'kodeKelas' => 'SI2201',
                'kapasitas' => '40',
                'kodeMK' => 'IS184203',
                'kelas' => 'A',
                'dosenNRP' => '5026202',
            ],
            [
                'kodeKelas' => 'SI2201',
                'kapasitas' => '40',
                'kodeMK' => 'IS184203',
                'kelas' => 'B',
                'dosenNRP' => '5026202',
            ],
            [
                'kodeKelas' => 'SI2201',
                'kapasitas' => '40',
                'kodeMK' => 'IS184203',
                'kelas' => 'C',
                'dosenNRP' => '5026202',
            ],
            [
                'kodeKelas' => 'SI2201',
                'kapasitas' => '40',
                'kodeMK' => 'IS184203',
                'kelas' => 'D',
                'dosenNRP' => '5026224',
            ],
            [
                'kodeKelas' => 'SI2201',
                'kapasitas' => '40',
                'kodeMK' => 'IS184203',
                'kelas' => 'I',
                'dosenNRP' => '5026224',
            ],
            [
                'kodeKelas' => 'SI1101',
                'kapasitas' => '40',
                'kodeMK' => 'IS184307',
                'kelas' => 'A',
                'dosenNRP' => '5026201',
            ],
            [
                'kodeKelas' => 'SI1101',
                'kapasitas' => '40',
                'kodeMK' => 'IS184307',
                'kelas' => 'B',
                'dosenNRP' => '5026201',
            ],
            [
                'kodeKelas' => 'SI1101',
                'kapasitas' => '40',
                'kodeMK' => 'IS184307',
                'kelas' => 'C',
                'dosenNRP' => '5026201',
            ],
            [
                'kodeKelas' => 'SI1101',
                'kapasitas' => '40',
                'kodeMK' => 'IS184307',
                'kelas' => 'D',
                'dosenNRP' => '5026203',
            ],
            [
                'kodeKelas' => 'SI1101',
                'kapasitas' => '40',
                'kodeMK' => 'IS184307',
                'kelas' => 'I',
                'dosenNRP' => '5026203',
            ],
            [
                'kodeKelas' => 'SI2201',
                'kapasitas' => '40',
                'kodeMK' => 'IS184101',
                'kelas' => 'A',
                'dosenNRP' => '5026213',
            ],
            [
                'kodeKelas' => 'SI2201',
                'kapasitas' => '40',
                'kodeMK' => 'IS184101',
                'kelas' => 'B',
                'dosenNRP' => '5026213',
            ],
            [
                'kodeKelas' => 'SI2201',
                'kapasitas' => '40',
                'kodeMK' => 'IS184101',
                'kelas' => 'C',
                'dosenNRP' => '5026213',
            ],
            [
                'kodeKelas' => 'SI2201',
                'kapasitas' => '40',
                'kodeMK' => 'IS184101',
                'kelas' => 'D',
                'dosenNRP' => '5026224',
            ],
            [
                'kodeKelas' => 'SI2201',
                'kapasitas' => '40',
                'kodeMK' => 'IS184101',
                'kelas' => 'I',
                'dosenNRP' => '5026224',
            ],
            [
                'kodeKelas' => 'SI2202',
                'kapasitas' => '40',
                'kodeMK' => 'IS184305',
                'kelas' => 'A',
                'dosenNRP' => '5026202',
            ],
            [
                'kodeKelas' => 'SI2202',
                'kapasitas' => '40',
                'kodeMK' => 'IS184305',
                'kelas' => 'B',
                'dosenNRP' => '5026202',
            ],
            [
                'kodeKelas' => 'SI2202',
                'kapasitas' => '40',
                'kodeMK' => 'IS184305',
                'kelas' => 'C',
                'dosenNRP' => '5026202',
            ],
            [
                'kodeKelas' => 'SI2202',
                'kapasitas' => '40',
                'kodeMK' => 'IS184305',
                'kelas' => 'D',
                'dosenNRP' => '5026226',
            ],
            [
                'kodeKelas' => 'SI2202',
                'kapasitas' => '40',
                'kodeMK' => 'IS184305',
                'kelas' => 'I',
                'dosenNRP' => '5026226',
            ],
            [
                'kodeKelas' => 'SI4102',
                'kapasitas' => '40',
                'kodeMK' => 'IS184411',
                'kelas' => 'A',
                'dosenNRP' => '5026212',
            ],
            [
                'kodeKelas' => 'SI4102',
                'kapasitas' => '40',
                'kodeMK' => 'IS184411',
                'kelas' => 'B',
                'dosenNRP' => '5026212',
            ],
            [
                'kodeKelas' => 'SI4102',
                'kapasitas' => '40',
                'kodeMK' => 'IS184411',
                'kelas' => 'C',
                'dosenNRP' => '5026212',
            ],
            [
                'kodeKelas' => 'SI4102',
                'kapasitas' => '40',
                'kodeMK' => 'IS184411',
                'kelas' => 'D',
                'dosenNRP' => '5026212',
            ],
            [
                'kodeKelas' => 'SI4102',
                'kapasitas' => '40',
                'kodeMK' => 'IS184411',
                'kelas' => 'I',
                'dosenNRP' => '5026212',
            ],
            [
                'kodeKelas' => 'SI4102',
                'kapasitas' => '40',
                'kodeMK' => 'IS184621',
                'kelas' => 'A',
                'dosenNRP' => '5026221',
            ],
            [
                'kodeKelas' => 'SI4102',
                'kapasitas' => '40',
                'kodeMK' => 'IS184621',
                'kelas' => 'B',
                'dosenNRP' => '5026221',
            ],
            [
                'kodeKelas' => 'SI4102',
                'kapasitas' => '40',
                'kodeMK' => 'IS184621',
                'kelas' => 'C',
                'dosenNRP' => '5026221',
            ],
            [
                'kodeKelas' => 'SI4102',
                'kapasitas' => '40',
                'kodeMK' => 'IS184621',
                'kelas' => 'D',
                'dosenNRP' => '5026226',
            ],
            [
                'kodeKelas' => 'SI4102',
                'kapasitas' => '40',
                'kodeMK' => 'IS184621',
                'kelas' => 'I',
                'dosenNRP' => '5026226',
            ]
        ]);
    }
}
